=== Sakine-Ayoub1/projet-WS/Technologie XML/releve.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xsd:element name="releve">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="dateReleve" type="xsd:date"></xsd:element>
            <xsd:element name="solde" type="xsd:double"></xsd:element>
            <xsd:element name="operations" type="T_OPS"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>
    
<xsd:complexType name="T_OPS">
    <xsd:sequence>
        <xsd:element name="operation" type="T_OP" minOccurs="1" maxOccurs="unbounded"></xsd:element>
    </xsd:sequence>
    <xsd:attribute name="dateDebut" type="xsd:date" use="required"></xsd:attribute>
    <xsd:attribute name="dateFin" type="xsd:date" use="required"></xsd:attribute>
</xsd:complexType> 
    
<xsd:complexType name="T_OP">
    <xsd:attribute name="type" use="required">
        <xsd:simpleType>
            <xsd:restriction base="xsd:string">
                <xsd:enumeration value="credit"></xsd:enumeration>
                <xsd:enumeration value="debit"></xsd:enumeration>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:attribute>
    <xsd:attribute name="date" type="xsd:date"></xsd:attribute>
    <xsd:attribute name="montant" type="xsd:double"></xsd:attribute>
    <xsd:attribute name="description" type="xsd:string"></xsd:attribute>
</xsd:complexType>    

</xsd:schema>

=== Sakine-Ayoub1/projet-WS/Technologie XML/releveXsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<releve xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/isicod/Desktop/Master/semestre%201/Module%20web%20services/Projet%20WS/Technologie%20XML/releve.xsd">
    <dateReleve>2021-11-10</dateReleve>
    <solde>14500</solde>
    <operations dateDebut="2021-01-01" dateFin="2021-01-30">
        <operation type="credit" date="2021-01-01" montant="9000" description="Vers EspÃ¨ce"></operation>
        <operation type="debit" date="2021-01-11" montant="3400" description="assurance"></operation>
        <operation type="debit" date="2021-01-15" montant="120" description="Cheque"></operation>
        <operation type="credit" date="2021-01-25" montant="70000" description="assurance"></operation>
    </operations>
</releve>
